--- #YAML:1.0
name:               Gtk2-Ex-Geo
version:            0.65
abstract:           The main module to use for geospatial applications
author:
    - Ari Jolma <ari.jolma @ aalto.fi>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::Depends:    0
    ExtUtils::PkgConfig:  0
    Gtk2:                 0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:             5.57
    Geo::OGC::Geometry:   0
    Glib:                 0
    Graphics::ColorUtils:  0
    Gtk2:                 0
    Gtk2::GladeXML:       0
    Scalar::Util:         0
    Test::More:           0
resources:
    repository:  http://svn.osgeo.org/geoinformatica/Gtk2-Ex-Geo/trunk/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
