# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-Geo
version:      0.61
version_from: lib/Gtk2/Ex/Geo.pm
installdirs:  site
requires:
    ExtUtils::Depends:             0
    ExtUtils::PkgConfig:           0
    Geo::OGC::Geometry:            0
    Graphics::ColorUtils:          0
    Gtk2::GladeXML:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
