--- #YAML:1.0
name:                Gtk2-Ex-Geo
version:             0.56
abstract:            The main module to use for geospatial applications
license:             ~
author:              
    - Ari Jolma <ari.jolma @ tkk.fi>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
